# Plugins are rather limited in Github Pages, though a lot of useful ones are supported, check out:
# https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins
plugins:
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-redirect-from

####################
###### routes ######
####################

url: https://safing.io
base_url: "/" # the subpath of your site, e.g. /blog

### assets
assets_url: /assets/
img_url: /assets/img/
video_url: /assets/video/
vendor_url: /vendor/

### pages
about_url: /about/
blog_url: /blog/
backlog_url: /backlog/
community_hub_url: /community-hub/
contact_url: /contact/
esa_bic_url: /esa-bic/
help_url: /support/
newsletter_url: /newsletter/
ownership_url: /ownership/
business_model_url: /business-model/
podcast_url: /podcast/
portmaster_url: /portmaster/
download_url: /download/
pricing_url: /pricing/
features_url: /features/
privacy_url: /privacy/
next_page_url: /next/
spn_url: /spn/
team_url: /team/
jobs_url: /jobs/
terms_url: /terms/
video_url: /video/
whitepaper_url: /files/whitepaper/Gate17.pdf
vpn_comparison_url: /blog/2022/09/06/spn-vs-vpns/
tor_comparison_url: /blog/2020/01/22/how-the-spn-compares-to-tor/
pihole_comparison_url: /blog/2021/12/09/portmaster-vs-pi-hole/
simplewall_comparison_url: /blog/2022/04/11/portmaster-vs-simplewall/
glasswire_comparison_url: /blog/2022/08/17/portmaster-vs-glasswire/

### external
docs_url: https://docs.safing.io/

account_server_url: https://account.safing.io/
account_server_redeem_url: https://account.safing.io/redeem

assets_server_url: https://assets.safing.io/
company_agreement_url: https://www.firmenmonitor.at/Secure/CompanyDetail.aspx?CID=761761

download_linux_deb_url: https://updates.safing.io/latest/linux_amd64/packages/portmaster-installer.deb
download_linux_rpm_url: https://updates.safing.io/latest/linux_amd64/packages/portmaster-installer.rpm
download_windows_url: https://updates.safing.io/latest/windows_amd64/packages/portmaster-installer.exe
download_arch_url: https://aur.archlinux.org/packages/portmaster-stub-bin

installer_checksums: https://github.com/safing/checksums/

img_shields_io_stars_url: https://img.shields.io/github/stars/safing/portmaster?color=%23fff0&label=%20&style=for-the-badge
img_shields_io_release_url: https://img.shields.io/github/v/release/safing/portmaster?color=%23fff0&label=%20&style=for-the-badge

docs_install_linux_url: https://docs.safing.io/portmaster/install/linux
docs_install_windows_url: https://docs.safing.io/portmaster/install/windows
docs_code_of_conduct_url: https://docs.safing.io/community/code-of-conduct

spn_alpha_status_page_url: https://docs.safing.io/spn/alpha/status

kickstarter_url: https://www.kickstarter.com/projects/safingio/spn
reddit_url: https://reddit.com/r/safing
twitter_url: https://twitter.com/SafingIO
discord_url: https://discord.gg/safing
github_url: https://github.com/safing

youtube_channel_url: https://www.youtube.com/c/SafingIO
invidious_channel_url: https://invidious.snopyta.org/channel/UC_6TW053IlS4M22g7CxnukA

youtube_portmaster_tut_getting_started: /video/2022/03/28/portmaster-intro-getting-started/
youtube_portmaster_tut_filter_lists: /video/2022/04/04/portmaster-intro-filter-lists/
youtube_spn_tut_multi_identity: /video/2022/03/21/spn-intro-be-everywhere/

seen_itsfoss_url: https://news.itsfoss.com/portmaster-1-release/
seen_ghacks_url: https://www.ghacks.net/2022/11/08/portmaster-1-0-released-open-source-application-firewall/
seen_techlore_url: https://www.youtube.com/watch?v=E8cTRhGtmcM
seen_privacytools_url: https://www.privacytools.io/windows/

### donations
donations:
  bitcoin:
    url: https://www.blockchain.com/btc/address/1AosdDyzd8PVUFTUEXoaJHTyPVHuKQxdmq?filter=2
  paypal:
    url: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2QHNM78H9YC9L&source=url

###########################
###### site settings ######
###########################

title: Safing
encoding: "utf-8"
lang: "en"
description: > # this means to ignore newlines until "base_url:"
  Portmaster is a free and open-source application that puts you back in charge over all your computer's network connections. Increase your privacy and security. Get peace of mind.

markdown: kramdown

excerpt_separator: "<!--break-->"
inter_post_navigation: false

email: hello@safing.io
emailobfuscated: "=b!isfg>#nbjmup;ifmmpAtbgjoh/jp#?ifmmpAtbgjoh/jp=0b?"

##############################
###### OGP settings ######
##############################

twitter_username: "@SafingIO"
twitter_card_type: "summary_large_image"

###################################
###### collection options ######
###################################

collections:
  jobs:
    output: true
    permalink: /jobs/:title/
  publications:
    output: true

defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      permalink: /:categories/:year/:month/:day/:title/
      type: "publication"


###################################
###### media/content options ######
###################################

last_progress_update_on: "04. November 2022"
last_finances_update_on: "March 2022"

##############################
###### Podcast settings ######
##############################

podcast_itunes_url: https://podcasts.apple.com/podcast/id1480027286
podcast_feed_url: /podcast.xml
podcast_album_art: /assets/podcast/img/cover.jpg
podcast_owner: 'Safing'
podcast_email: 'hello@safing.io'
podcast_category: Business
podcast_subcategory_one: Entrepreneurship
podcast_explicit: "no"
podcast_author: safing.io
podcast_title: "Coding Freedom - The Safing Podcast"
podcast_subtitle: "Join ordinary people who fight Mass Surveillance because they Love Freedom."
podcast_description: "Discontent with the global state of mass surveillance and its negative impact on our lives, the Safing team decided it was time to do something about it. Take part of the journey and explore the behind-the-scenes: How do you fund a privacy company? Why are deadlines always unrealistic? And ultimately, what is the solution to the privacy dilemma?"
podcast_summary: "Discontent with the global state of mass surveillance and its negative impact on our lives, the Safing team decided it was time to do something about it. Take part of the journey and explore the behind-the-scenes: How do you fund a privacy company? Why are deadlines always unrealistic? And ultimately, what is the solution to the privacy dilemma?"

##############################
###### Blog settings ######
##############################

blog_feed_url: /blog.xml
