blank_issues_enabled: true
contact_links:

- name: "ğŸ“‘ Create Issue for the Docs"
  url: https://github.com/safing/docs/issues/new/choose
  about: "Create issue for everything related to Documentation"

# - name: "ğŸ” Create Issue for the Website"
#   url: https://github.com/safing/website/issues/new/choose
#   about: "Create issue for everything related to Safing's main website"

- name: "Contribution Guideline"
  url: https://wiki.safing.io/en/Contribute
  about: Learn how to best contribute and make sure your work is aligned with Safingâ€™s current goals and focus

- name: "Code of Conduct"
  url: https://wiki.safing.io/en/CodeOfConduct
  about: Be nice to other community members
